# Generated by Django 4.1 on 2022-10-09 05:38

import api.models.category
import api.models.company
import api.models.customer
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=api.models.category.Category.get_category_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.models.company.get_company_image_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=api.models.company.get_company_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usertype', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('broker', 'Broker')], default='customer', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=255, unique=True)),
                ('isMobileNumberVerified', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to=api.models.customer.get_profile_image_path)),
                ('provider', models.CharField(choices=[('oauth', 'Oauth'), ('facebook', 'Facebook'), ('google', 'Google')], default='oauth', max_length=255)),
                ('provider1', models.CharField(choices=[('oauth', 'Oauth'), ('facebook', 'Facebook'), ('google', 'Google')], default='oauth', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
