# Generated by Django 4.1 on 2022-11-23 04:42

import api.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usertype', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('broker', 'Broker')], default='customer', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=255, unique=True)),
                ('isMobileNumberVerified', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to=api.models.customer.get_profile_image_path)),
                ('provider', models.CharField(choices=[('oauth', 'Oauth'), ('facebook', 'Facebook'), ('google', 'Google')], default='oauth', max_length=255)),
                ('provider1', models.CharField(choices=[('oauth', 'Oauth'), ('facebook', 'Facebook'), ('google', 'Google')], default='oauth', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
